In [ ]:
%tensorflow_version 1.x

TensorFlow 1.x selected.


In [ ]:
from google.colab import drive
drive.mount('/content/drivee')

Mounted at /content/drivee


In [ ]:
!mkdir WIDER_train

In [ ]:
!mkdir WIDER_train/images

In [ ]:
!cp -r /content/drivee/MyDrive/final_denoised /content/WIDER_train/images

In [ ]:
!mkdir WIDER_val

In [ ]:
!mkdir WIDER_val/images

In [ ]:
!cp -r /content/drivee/MyDrive/Validation /content/WIDER_val/images

In [ ]:
!git clone https://github.com/akofman/wider-face-pascal-voc-annotations.git

Cloning into 'wider-face-pascal-voc-annotations'...
remote: Enumerating objects: 16128, done.
remote: Counting objects: 100% (3/3), done.
remote: Compressing objects: 100% (2/2), done.
remote: Total 16128 (delta 0), reused 0 (delta 0), pack-reused 16125
Receiving objects: 100% (16128/16128), 6.07 MiB | 20.00 MiB/s, done.
Resolving deltas: 100% (15830/15830), done.


In [ ]:
import os
len(os.listdir("/content/WIDER_val/images/Validation"))

98

In [ ]:
cd wider-face-pascal-voc-annotations/


/content/wider-face-pascal-voc-annotations


In [ ]:
!mkdir ../billu_anno_train/

In [ ]:
!mkdir ../billu_anno_val/

In [ ]:
'while i < int(nbBndboxes) or i == 0'

In [ ]:
!python convert.py -ap /content/wider_train_bbx_gt_final.txt -tp /content/billu_anno_train/ -ip /content/WIDER_train/images


Streaming output truncated to the last 5000 lines.
3978.png => /content/billu_anno_train/3978.png
4016.png => /content/billu_anno_train/4016.png
794.png => /content/billu_anno_train/794.png
2015.png => /content/billu_anno_train/2015.png
3026.png => /content/billu_anno_train/3026.png
228.png => /content/billu_anno_train/228.png
4516.png => /content/billu_anno_train/4516.png
5214.png => /content/billu_anno_train/5214.png
1714.png => /content/billu_anno_train/1714.png
4342.png => /content/billu_anno_train/4342.png
1803.png => /content/billu_anno_train/1803.png
4524.png => /content/billu_anno_train/4524.png
2528.png => /content/billu_anno_train/2528.png
3386.png => /content/billu_anno_train/3386.png
4409.png => /content/billu_anno_train/4409.png
4637.png => /content/billu_anno_train/4637.png
5622.png => /content/billu_anno_train/5622.png
2374.png => /content/billu_anno_train/2374.png
4878.png => /content/billu_anno_train/4878.png
5796.png => /content/billu_anno_train/5796.png
2036.png => /

In [ ]:
!python convert.py -ap /content/wider_val_bbx_gt_final.txt -tp /content/billu_anno_val/ -ip /content/WIDER_val/images


54.png => /content/billu_anno_val/54.png
63.png => /content/billu_anno_val/63.png
88.png => /content/billu_anno_val/88.png
85.png => /content/billu_anno_val/85.png
95.png => /content/billu_anno_val/95.png
24.png => /content/billu_anno_val/24.png
49.png => /content/billu_anno_val/49.png
46.png => /content/billu_anno_val/46.png
59.png => /content/billu_anno_val/59.png
82.png => /content/billu_anno_val/82.png
83.png => /content/billu_anno_val/83.png
78.png => /content/billu_anno_val/78.png
28.png => /content/billu_anno_val/28.png
37.png => /content/billu_anno_val/37.png
16.png => /content/billu_anno_val/16.png
39.png => /content/billu_anno_val/39.png
36.png => /content/billu_anno_val/36.png
12.png => /content/billu_anno_val/12.png
80.png => /content/billu_anno_val/80.png
8.png => /content/billu_anno_val/8.png
60.png => /content/billu_anno_val/60.png
69.png => /content/billu_anno_val/69.png
96.png => /content/billu_anno_val/96.png
42.png => /content/billu_anno_val/42.png
74.png => /content

In [ ]:
!cp -r /content/billu_anno_train /content/WIDER_train/images

In [ ]:
!cp -r /content/billu_anno_val /content/WIDER_val/images

In [ ]:
cd ..

/content


In [ ]:
!git clone https://github.com/Media-Smart/vedadet.git

Cloning into 'vedadet'...
remote: Enumerating objects: 974, done.
remote: Counting objects: 100% (76/76), done.
remote: Compressing objects: 100% (63/63), done.
remote: Total 974 (delta 28), reused 30 (delta 12), pack-reused 898
Receiving objects: 100% (974/974), 1.18 MiB | 4.67 MiB/s, done.
Resolving deltas: 100% (412/412), done.


In [ ]:
cd vedadet/

/content/vedadet


In [ ]:
vedadet_root="/content/vedadet"


In [ ]:
!pip install -r requirements/build.txt


In [ ]:
!pip install -v -e .


Created temporary directory: /tmp/pip-ephem-wheel-cache-qbe0es4j
Created temporary directory: /tmp/pip-req-tracker-l4foa_m2
Created requirements tracker '/tmp/pip-req-tracker-l4foa_m2'
Created temporary directory: /tmp/pip-install-0cct5ydv
Obtaining file:///content/vedadet
  Added file:///content/vedadet to build tracker '/tmp/pip-req-tracker-l4foa_m2'
    Running setup.py (path:/content/vedadet/setup.py) egg_info for package from file:///content/vedadet
    Running command python setup.py egg_info
    running egg_info
    creating vedadet.egg-info
    writing vedadet.egg-info/PKG-INFO
    writing dependency_links to vedadet.egg-info/dependency_links.txt
    writing requirements to vedadet.egg-info/requires.txt
    writing top-level names to vedadet.egg-info/top_level.txt
    writing manifest file 'vedadet.egg-info/SOURCES.txt'
    adding license file 'LICENSE' (matched pattern 'LICEN[CS]E*')
    writing manifest file 'vedadet.egg-info/SOURCES.txt'
    /usr/local/lib/python3.7/dist-pac

In [ ]:
import os

In [ ]:
for count, filename in enumerate(os.listdir("/content/WIDER_train/images/Annotations")):

  src ='/content/WIDER_train/images/Annotations/'+ filename
  f = filename.split(".")[0]
  dst ="/content/WIDER_train/images/Annotations/"+f+".xml"
  # rename() function will
  # rename all the files
  os.rename(src, dst)

In [ ]:
os.listdir("/content/WIDER_val/Annotations")

[]

In [ ]:
for count, filename in enumerate(os.listdir("/content/WIDER_val/images/Annotations")):

  src ='/content/WIDER_val/images/Annotations/'+ filename
  f = filename.split(".")[0]
  dst ="/content/WIDER_val/images/Annotations/"+f+".xml"
  # rename() function will
  # rename all the files
  os.rename(src, dst)

FileNotFoundError: ignored

In [ ]:
!mkdir data

In [ ]:
!mkdir data/WIDERFace

In [ ]:
!cp -r /content/WIDER_train/WIDER_train /content/vedadet/data/WIDERFace

In [ ]:
!cp -r /content/WIDER_val/WIDER_val /content/vedadet/data/WIDERFace

In [ ]:
cd ..

/content


In [ ]:
cd vedadet/

/content/vedadet


In [ ]:
!bash configs/trainval/tinaface/gen_xml_name_txt.sh


In [ ]:
/content/vedadet/data/WIDERFace/WIDER_val/0--Parade

In [ ]:
for count, filename in enumerate(os.listdir("/content/vedadet/data/WIDERFace/WIDER_train/0--Parade")):

  src ='/content/vedadet/data/WIDERFace/WIDER_train/0--Parade/'+ filename
  f = filename.split(".")[0]
  dst ="/content/vedadet/data/WIDERFace/WIDER_train/0--Parade/"+f+".jpg"
  # rename() function will
  # rename all the files
  os.rename(src, dst)

In [ ]:
for count, filename in enumerate(os.listdir("/content/vedadet/data/WIDERFace/WIDER_val/0--Parade")):

  src ='/content/vedadet/data/WIDERFace/WIDER_val/0--Parade/'+ filename
  f = filename.split(".")[0]
  dst ="/content/vedadet/data/WIDERFace/WIDER_val/0--Parade/"+f+".jpg"
  # rename() function will
  # rename all the files
  os.rename(src, dst)

In [ ]:
!mkdir workdir

In [ ]:
!cp /content/drivee/MyDrive/ckpts2/epoch_67_weights.pth /content/vedadet/workdir

In [ ]:
!cp /content/drivee/MyDrive/ckpts2/epoch_67_optim.pth /content/vedadet/workdir

In [ ]:
!cp /content/drivee/MyDrive/ckpts2/epoch_67_meta.pth /content/vedadet/workdir

In [ ]:
mean = array([51.2388966 , 42.83849231, 44.20246694])


In [ ]:
array([38.68637351, 38.73133735, 36.8817875 ])


In [ ]:
CUDA_VISIBLE_DEVICES="0"
!python tools/trainval.py configs/trainval/tinaface/tinaface_r50_fpn_bn.py --workdir /content/vedadet/workdir


2021-05-01 15:14:47,344 - vedadet - WARNING - EvalHook is not in modes ['train']
2021-05-01 15:14:47,344 - vedadet - INFO - Loading weights from /content/vedadet/workdir/epoch_67_weights.pth
2021-05-01 15:14:47,545 - vedadet - INFO - Loading optimizer from /content/vedadet/workdir/epoch_67_optim.pth
2021-05-01 15:14:47,801 - vedadet - INFO - Loading meta from /content/vedadet/workdir/epoch_67_meta.pth
/usr/local/lib/python3.7/dist-packages/torch/nn/functional.py:3458: UserWarning: Default upsampling behavior when mode=bilinear is changed to align_corners=False since 0.4.0. Please specify align_corners=True if the old behavior is desired. See the documentation of nn.Upsample for details.
  "See the documentation of nn.Upsample for details.".format(mode)
2021-05-01 15:15:54,538 - vedadet - INFO - Epoch [68][100/1476] lr: 0.003273, loss_cls: 0.1671, loss_bbox: 0.5066, loss_iou: 0.5456, loss: 1.2194
2021-05-01 15:17:01,348 - vedadet - INFO - Epoch [68][200/1476] lr: 0.003273, loss_cls: 0.1

In [ ]:
CUDA_VISIBLE_DEVICES="0" 
!python tools/test.py configs/trainval/tinaface/tinaface_r50_fpn_bn.py /content/drivee/MyDrive/mw/tinaface_r50_fpn_bn.pth


completed: 0, elapsed: 0sTraceback (most recent call last):
  File "tools/test.py", line 74, in <module>
    main()
  File "tools/test.py", line 70, in main
    data_loader.dataset.evaluate(results)
  File "/content/vedadet/vedadet/datasets/custom.py", line 397, in evaluate
    logger=logger)
  File "/content/vedadet/vedadet/misc/evaluation/mean_ap.py", line 308, in eval_map
    num_classes = len(det_results[0])  # positive class num
IndexError: list index out of range


In [ ]:
import cv2

In [ ]:
image = cv2.imread("/content/WIDER_val/images/Validation/1.png")


In [ ]:
image.shape

(720, 1080, 3)

In [ ]:
cv2.meanStdDev(image)

(array([[49.38386317],
        [52.38473508],
        [59.56698945]]), array([[41.69897633],
        [46.2355994 ],
        [46.33281755]]))

In [ ]:
import tqdm

In [ ]:
def cal_mean_std(images_dir):
    """
    Given the root directory of the data picture, calculate the overall mean and variance of the picture
    : param images_dir:
    :return:
    """
    img_filenames = os.listdir(images_dir)
    m_list, s_list = [], []
    for img_filename in tqdm.tqdm(img_filenames):
        img = cv2.imread(images_dir + '/' + img_filename)
        img = img / 255.0
        m, s = cv2.meanStdDev(img)

        m_list.append(m.reshape((3,)))
        s_list.append(s.reshape((3,)))
        # print(m_list)
    m_array = np.array(m_list)
    s_array = np.array(s_list)
    m = m_array.mean(axis=0, keepdims=True)
    s = s_array.mean(axis=0, keepdims=True)
    print('mean: ',m[0][::-1])
    print('std:  ',s[0][::-1])
    return m 

In [ ]:
import os

In [ ]:
import numpy as np


In [ ]:
cal_mean_std("/content/WIDER_train/images/final_denoised")


100%|██████████| 5902/5902 [02:34<00:00, 38.24it/s]

mean:  [0.20093685 0.16799409 0.17334301]
std:   [0.15171127 0.1518876  0.14463446]


array([[0.17334301, 0.16799409, 0.20093685]])

In [ ]:
means = [0, 0, 0]
stdevs = [0, 0, 0]
index = 1
num_imgs = 0

for file in os.listdir("/content/WIDER_train/images/0--Parade"):
  print('{}/{}'.format(index, len(os.listdir("/content/WIDER_train/images/0--Parade"))))
  index += 1
  a = os.path.join("/content/WIDER_train/images/0--Parade",file)
  # print(a[:-1])
  num_imgs += 1
  print(a)
  img = cv2.imread(a)
  img = np.asarray(img)
  img_ = img.astype(np.float32)
  for i in range(3):
    means[i] += img_[:,:,i].mean()
    stdevs[i] += img_[:,:,i].std()

  print(num_imgs)
means.reverse()
stdevs.reverse()

means = np.asarray(means) / num_imgs
stdevs = np.asarray(stdevs) / num_imgs

Streaming output truncated to the last 5000 lines.
/content/WIDER_train/images/0--Parade/1665.png
4236
4237/5902
/content/WIDER_train/images/0--Parade/1716.png
4237
4238/5902
/content/WIDER_train/images/0--Parade/1748.png
4238
4239/5902
/content/WIDER_train/images/0--Parade/1705.png
4239
4240/5902
/content/WIDER_train/images/0--Parade/4092.png
4240
4241/5902
/content/WIDER_train/images/0--Parade/1242.png
4241
4242/5902
/content/WIDER_train/images/0--Parade/2998.png
4242
4243/5902
/content/WIDER_train/images/0--Parade/3257.png
4243
4244/5902
/content/WIDER_train/images/0--Parade/2010.png
4244
4245/5902
/content/WIDER_train/images/0--Parade/627.png
4245
4246/5902
/content/WIDER_train/images/0--Parade/5607.png
4246
4247/5902
/content/WIDER_train/images/0--Parade/834.png
4247
4248/5902
/content/WIDER_train/images/0--Parade/3232.png
4248
4249/5902
/content/WIDER_train/images/0--Parade/1107.png
4249
4250/5902
/content/WIDER_train/images/0--Parade/880.png
4250
4251/5902
/content/WIDER_train/i

In [ ]:
means

array([51.2388966 , 42.83849231, 44.20246694])

In [ ]:
stdevs

array([38.68637351, 38.73133735, 36.8817875 ])